### ISSUE TITLE
Play videos in windowed mode possible / planned?

### ISSUE THREAD

**Issue by bernddd** [OtherCrashOverride/c2play#14]
Hello,

c2play works already great for my videos. 
is there a possibility to play videos in windowed mode?

Greetings Bernd

**Comment by OtherCrashOverride** [comment]
Window mode was investigated.  While it is possible to play video in windowed mode, it causes everything to render incorrectly due to the required transparency.  The X11 driver and/or pixman will need to be modified to write proper alpha values to the frame buffer.

**Comment by OtherCrashOverride** [comment]
Duplicate of #6
