### ISSUE TITLE
Output delay after start of decoding

### ISSUE THREAD

**Issue by slavaman** [OtherCrashOverride/c2play#25]
Hello! Found the save issue as inside [hello_videocube](https://github.com/OtherCrashOverride/hello_videocube/issues/3) After sending h264 bitstream to decoder, we get result on a screen after 100-200ms delay. Then the delay between sending data to decoder and otput to screen is about 30 frames (tested with 2k resolution). Is it a bug or a feature? Can I reduce this latency? Is there any tune up features in amlcodec to get zero-buffering? Is there any way to get 1encodedFrameIn=>1decodedFrameOnScreen?
Thnk you!

p.s. This issue is also observerd in
[Odroid C2 forum post#1](http://forum.odroid.com/viewtopic.php?f=135&t=22418)
[Odroid C2 forum post#2](http://forum.odroid.com/viewtopic.php?f=135&t=22422)

**Comment by OtherCrashOverride** [comment]
c2play is not intended to be a "real time" player.  It will add or remove latency to maintain synchronization of the input streams.  It buffers input, by design, to achieve this goal.
