### ISSUE TITLE
volume up/down support ?

### ISSUE THREAD

**Issue by rafaelSorel** [OtherCrashOverride/c2play#29]
I tried to integrate volume up/down support with no success.
alsamixer seems to have no effect even using the command line.

The only thing I have found that could control the sound is **/sys/class/amaudio**, I could control the **mute/unmute** but not the volume.

Thanks,

**Comment by OtherCrashOverride** [comment]
Volume support is handled by the platform environment being used.  C2play uses the ALSA API; however, this typically gets re-rerouted through PulseAudio on many distributions.

**Comment by rafaelSorel** [comment]
I use a ubuntu server without any desktop environment, only fbdev one, so pulseaudio is not used in my case, I wanted to use the alsa-utils to control volume, but each time I tried to change the volume through amixer, it get back to the default value right after my change.

**Comment by rafaelSorel** [comment]
Well I have found the issue, it was the alsa conf files that were miss configured.
