### ISSUE TITLE
Looping a video results in blank screen

### ISSUE THREAD

**Issue by artelse** [OtherCrashOverride/c2play#30]
Am having a problem where I am trying to loop a video indefinitely in a kiosk style setting. After an indeterminate time it stalls in a blank screen. I compiled the next branch for fbdev and run on standard ubuntu headless odroid distro. The video is h264 in an mp4 container. Any ideas? Could it be a non standard codec setting perhaps? What is the preferred codec setting for c2play? Thanks!

**Comment by artelse** [comment]
Further testing the problem. It seems that  when c2play is started from the terminal and not remotely through SSH, the blank screen doesn't occur. This has been done with a small clip resulting in a high loop frequency. Will test some more with a larger clip. What may happen is that c2play somehow cannot output over SSH and craps out?

Update: did more testing with a larger file and no problems occur when started from the local terminal.

**Comment by OtherCrashOverride** [comment]
This is most likely the console screen saver.  The fbdev version attempts to disable it:
https://github.com/OtherCrashOverride/c2play/blob/534cac8f965bd7062d99cf2860a8f7918a06332d/src/UI/Fbdev/FbdevAmlWindow.h#L64-L77

This may be failing if running over SSH.  The console screen save can also be disabled on the kernel command line.
