### ISSUE TITLE
Compilation error c2play-x11

### ISSUE THREAD

**Issue by jimchristo** [OtherCrashOverride/c2play#4]
When i run this command :(make c2play-x11) i get the following message:

==== Building c2play-x11 (debug) ====
main.cpp
In file included from ../../src/Media/MediaPlayer.h:23:0,
                 from ../../src/main.cpp:39:
../../src/Media/SubtitleCodecElement.h:25:21: fatal error: ass/ass.h: No such file or directory
compilation terminated.
c2play-x11.make:163: recipe for target 'obj/Debug/c2play-x11/main.o' failed
make[1]: *** [obj/Debug/c2play-x11/main.o] Error 1
Makefile:20: recipe for target 'c2play-x11' failed
make: *** [c2play-x11] Error 2

what is going wrong?
Thank you in advance.

**Comment by OtherCrashOverride** [comment]
Ensure you have the development headers (libass-dev) installed as shown in the README.
https://github.com/OtherCrashOverride/c2play/blob/beta1/README
>Install dependencies:
>    sudo apt install libasound2-dev libavformat-dev libass-dev

**Comment by jimchristo** [comment]
Now the previous issue is ok. (In master branch there wasn't a readme file.Thank you for point out)

Now it prints the following:

In file included from ../../src/UI/Compositor.h:27:0,
                 from ../../src/UI/Compositor.cpp:17:
../../src/UI/Egl.h:22:21: fatal error: EGL/egl.h: No such file or directory
compilation terminated.


Thank you!

**Comment by jimchristo** [comment]
Nevermind,I run this command:
sudo apt-get install libglfw3-dev libgles2-mesa-dev

and now is ok.

Thank you very much for your support.
